import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";

import Header from '@/components/Header/Header'
import Footer from '@/components/Footer'

import { ChatWidget } from '@/components/chat-widget';
import { ContactWidget } from '@/components/contact-widget'

import { MobileNavs } from "@/components/mobile-nav";

import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { AuthProvider } from "./AuthContext";
import { CartProvider } from "./CartContext";
import { OAuth2RedirectHandler } from "./(auth)/_components/OAuth2RedirectHandler";
import { ExternalUserSessionBootstrap } from "./_components/ExternalUserSessionBootstrap";

const inter = Raleway({ subsets: ["latin"] });

// ✅ FIX: Replaced "Generated by create next app" with real metadata
export const metadata: Metadata = {
  title: {
    default: "West Can Auto Parts | Car & Truck Parts in Western Canada",
    template: "%s | West Can Auto Parts",
  },
  description:
    "West Can Auto Parts is Western Canada's trusted supplier of car and truck parts, shop supplies, and fluids. 40+ years of experience. In-store pickup & delivery available.",
  keywords: [
    "auto parts",
    "car parts",
    "truck parts",
    "replacement parts",
    "Western Canada auto parts",
    "West Can Auto Parts",
    "shop supplies",
    "fluids lubricants",
  ],
  authors: [{ name: "West Can Auto Parts", url: "https://westcanauto.store" }],
  creator: "West Can Auto Parts",
  publisher: "West Can Auto Parts",
  metadataBase: new URL("https://westcanauto.store"),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: "en_CA",
    url: "https://westcanauto.store",
    siteName: "West Can Auto Parts",
    title: "West Can Auto Parts | Car & Truck Parts in Western Canada",
    description:
      "Western Canada's trusted supplier of car and truck parts, shop supplies, and fluids. 40+ years of experience. In-store pickup & delivery available.",
    images: [
      {
        url: "/fav2.png",
        width: 1200,
        height: 630,
        alt: "West Can Auto Parts",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "West Can Auto Parts | Car & Truck Parts in Western Canada",
    description:
      "Western Canada's trusted supplier of auto parts. In-store pickup & delivery available.",
    images: ["/fav2.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: "/fav1.png",
    shortcut: "/fav1.png",
    apple: "/fav2.png",
  },
  verification: {
    // Add your Google Search Console verification token here
    // google: "your-google-verification-token",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <CartProvider>
          <OAuth2RedirectHandler>
            <ExternalUserSessionBootstrap />
            <Header />
            {children}
            <ContactWidget />
            <ChatWidget />
            <Footer />
            <MobileNavs />
          </OAuth2RedirectHandler>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}